server:
  port: 7005

spring:
  security:
    ignored: true
  datasource:
    url: jdbc:mysql://localhost:3306/bugtracker?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update